apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fxc2ck4c0-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:90d7f8718ca59d9bb1351309aad5e9cd49d1d8bc@sha256:52424f3051352636a9f76db71bdd26cfe70cf6bf964d240f9da5a195a9075d5f
          name: container-image
