apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fxc2ck4c0-nodejs
  janus-idp.io/tekton: fxc2ck4c0-nodejs
  backstage.io/kubernetes-id: fxc2ck4c0-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fxc2ck4c0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
